// app/layout.js

import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Footer from "@/components/Footer";



export const metadata = {
  title: "いべぽす",
  description: "Generated by create next app",
};

const notoSansJP = Noto_Sans_JP({
  subsets: [],
  weight: ["400", "700"],
  variable: "--font-noto-sans-jp",
});

export default function RootLayout({ children }) {


  return (
    <html lang="ja">
      <body className={`${notoSansJP.variable} antialiased`}>

          <Header />
          {children}
          <Footer />

      </body>
    </html>
  );
}