@startuml
hide circle
hide methods
skinparam linetype ortho

' entity active_storage_attachments {
'   *id : bigint
'   --
'   name : string
'   record_type : string
'   record_id : bigint
'   blob_id : bigint
'   created_at : datetime
' }

' entity active_storage_blobs {
'   *id : bigint
'   --
'   key : string
'   filename : string
'   content_type : string
'   metadata : text
'   service_name : string
'   byte_size : bigint
'   checksum : string
'   created_at : datetime
' }

' entity active_storage_variant_records {
'   *id : bigint
'   --
'   blob_id : bigint
'   variation_digest : string
' }

entity comments {
  *id : bigint
  --
  content : text
  event_id : bigint
  user_id : bigint
  created_at : datetime
  updated_at : datetime
}

entity events {
  *id : bigint
  --
  title : string
  date : datetime
  location : string
  description : text
  price : string
  user_id : bigint
  created_at : datetime
  updated_at : datetime
  image : string
  likes_count : bigint
}

entity likes {
  *id : bigint
  --
  user_id : bigint
  event_id : bigint
  created_at : datetime
  updated_at : datetime
}

entity users {
  *id : bigint
  --
  name : string
  email : string
  password_digest : string
  thumbnail : string
  description : text
  created_at : datetime
  updated_at : datetime
  authentication_token : string
}

' ' 外部キーの関係を定義
' active_storage_attachments }|--|| active_storage_blobs : "blob_id"
' active_storage_variant_records }|--|| active_storage_blobs : "blob_id"

comments }|--|| events : "event_id"
comments }|--|| users : "user_id"

likes }|--|| events : "event_id"
likes }|--|| users : "user_id"

events }|--|| users : "user_id"

@enduml