source 'https://rubygems.org'

# Rails Framework
gem 'rails', '~> 7.2.1', '>= 7.2.1.1'

# Database
gem 'sqlite3', '>= 1.4', groups: [:development, :test] # SQLite for development and test
gem 'mysql2', '>= 0.5'                                # MySQL for production

# Web Server
# gem 'unicorn'
gem 'puma'
# Authentication
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'

# Timezone Support (Windows specific)
gem 'tzinfo-data', platforms: %i[windows jruby]

# Performance
gem 'bootsnap', require: false

# Cross-Origin Resource Sharing (CORS)
gem 'rack-cors', require: 'rack/cors'

gem 'activestorage', require: 'active_storage/engine'


# Environment Variables for All Environments
gem 'dotenv-rails', require: false

# Development and Test Tools
group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude' # Debugging tool
  gem 'brakeman', require: false                                   # Security scanner
  gem 'rubocop-rails-omakase', require: false                     # Ruby/ Rails linting
  gem 'rubocop', require: false                                   # General linting
  gem 'rubocop-rails', require: false                             # Rails-specific linting
end
