import type { User } from "@/types/user.type";
import type { Event } from "@/types/event.type";

export const users: User[] = [
  {
    id: 1,
    name: "山田 太郎",
    email: "taro.yamada@example.com",
    description: "バックエンドエンジニア。Spring Boot と Rails が得意。",
    thumbnail_url: "https://example.com/thumbnails/taro.jpg",
  },
  {
    id: 2,
    name: "佐藤 花子",
    email: "hanako.sato@example.com",
    description: "フロントエンドエンジニア。React と Next.js が好き。",
    thumbnail_url: "https://example.com/thumbnails/hanako.png",
  },
  {
    id: 3,
    name: "鈴木 一郎",
    email: "ichiro.suzuki@example.com",
    description: null,
    thumbnail_url: null,
  },
];

export const events: Event[] = [
  {
    id: 1,
    title: "Next.js 勉強会",
    date: "2025-09-15",
    location: "東京 渋谷",
    description: "Next.js と TypeScript の最新機能を学ぶ会。",
    price: "無料",
    liked: false,
    likes_count: 12,
    image_url: "https://example.com/images/nextjs.png",
    user: users[1],
  },
  {
    id: 2,
    title: "クラウド勉強会 AWS編",
    date: "2025-09-20",
    location: "オンライン",
    description: "AWS の基礎から実践まで。",
    price: "500円",
    liked: true,
    likes_count: 25,
    user: users[0],
  },
  {
    id: 3,
    title: "Java Spring Boot Workshop",
    date: "2025-09-25",
    location: "大阪 梅田",
    description: "Spring Boot を使った API 開発。",
    price: "1000円",
    liked: false,
    likes_count: 8,
    user: users[0],
  },
  {
    id: 4,
    title: "React 初心者向けハンズオン",
    date: "2025-09-28",
    location: "名古屋",
    description: "React Hooks を体験しよう。",
    price: "無料",
    liked: true,
    likes_count: 30,
    user: users[1],
  },
  {
    id: 5,
    title: "音楽制作ワークショップ",
    date: "2025-10-01",
    location: "東京 下北沢",
    description: "DTM と DAW の実践講座。",
    price: "1500円",
    liked: false,
    likes_count: 5,
    image_url: "https://example.com/images/music.jpg",
    user: users[2],
  },
  {
    id: 6,
    title: "Docker 入門セミナー",
    date: "2025-10-05",
    location: "福岡",
    description: "Docker を基礎から学ぼう。",
    price: "2000円",
    liked: false,
    likes_count: 10,
    user: users[0],
  },
  {
    id: 7,
    title: "TypeScript 実践講座",
    date: "2025-10-08",
    location: "京都",
    description: "型安全なフロントエンド開発を目指す。",
    price: "1000円",
    liked: true,
    likes_count: 18,
    user: users[1],
  },
  {
    id: 8,
    title: "データベース設計勉強会",
    date: "2025-10-10",
    location: "オンライン",
    description: "ER 図と正規化の基礎。",
    price: "無料",
    liked: false,
    likes_count: 7,
    user: users[0],
  },
  {
    id: 9,
    title: "アニメソング DJ イベント",
    date: "2025-10-12",
    location: "秋葉原",
    description: "アニソン好き集まれ！",
    price: "2500円",
    liked: true,
    likes_count: 50,
    image_url: "https://example.com/images/anime-dj.jpg",
    user: users[2],
  },
  {
    id: 10,
    title: "エンジニア交流会",
    date: "2025-10-15",
    location: "札幌",
    description: "フリーランス・会社員問わず集まろう！",
    price: "無料",
    liked: false,
    likes_count: 20,
    user: users[1],
  },
];